apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hml
  namespace: self
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi      
  storageClassName: managed-nfs-storage

