server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  profiles:
    active: dev
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      connectionInitSqls: SELECT 1 FROM DUAL
      useGlobalDataSourceStat: true
  web:
    resources:
      cache:
        period: 31536000
        cache control:
          cache-public: true
          no-cache: false
          no-store: false
          must-revalidate: false
          max-age: 31536000
ebean:
  search:
    packages: com.cotte.estate.bean.pojo.doo
okhttp:
  connectTimeout: 30
  readTimeout: 30
  writeTimeout: 30
  maxIdleConnections: 200 # 连接池中整体的空闲连接的最大数量
  keepAliveDuration: 300 # 连接空闲时间最多为 300 秒